imports:
    - {resource: admin/}

#easy_admin:
#    site_name: 'Precieuses Timbres Admin'
#    design:
#        brand_color: 'red'
#    entities:
##        # List the entity class name you want to manage
#        - App\Entity\Commande
#        - App\Entity\DetailCommande
#        - App\Entity\Goodies
#        - App\Entity\Questionnaire
#        - App\Entity\User
#        - App\Entity\Stampwish
#
