easy_admin:
  design:
    brand_color: '#1ABC9C'

    menu:
      - label: 'PrécieusesTimbrées'
        icon: 'newspaper-o'
        children:
            -  {entity: 'User', icon: 'folder-open', label: 'User'}
            -  {entity: 'Commande', icon: 'folder-open', label: 'Commande'}
            -  {entity: 'DetailCommande', icon: 'folder-open', label: 'DetailCommande'}
            -  {entity: 'Goodies', icon: 'folder-open', label: 'Goodies'}
            -  {entity: 'Stampwish', icon: 'folder-open', label: 'Stampwish'}
            -  {entity: 'Questionnaire', icon: 'folder-open', label: 'Questionaire'}


      - label: 'Accès'
        icon: 'user'
        children:
           - {entity: 'User', icon: 'folder-open', label: 'Utilisateurs'}