easy_admin:
  entities:
    Goodies:
      class: App\Entity\Goodies
      form:
        fields:
          - {property: 'title', label: 'Titre'}
          - {property: 'photofile', type: 'file'}
          - {property: 'description', label: 'Description'}
          - {property: 'prix', label: 'Prix'}



      list:
        fields:
          - {property: 'title', label: 'Titre'}
          - {property: 'photo', type: 'photo', base_path: 'http://localhost:8000/uploads/images/' }
          - {property: 'description', label: 'Description'}
          - {property: 'prix', label: 'Prix'}
          - {property: 'update_at', label: 'Date'}



        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}