easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - {property: 'username', label: 'Utilisateurs'}
          - {property: 'email', label: 'Email'}
          - {property: 'Roles', type: 'collection'}

      list:
        fields:
          - {property: 'username', label: 'Utilisateurs'}
          - {property: 'email', label: 'Email'}

        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}